version: "2"
services:    
    rsyslog:
        image: viniciustorino/rsyslog-dockerized:latest
        container_name: rsyslog
        volumes: 
            - /var/log
        expose:
            - "514"
    ssh-trapper:
        image: viniciustorino/ssh-trapper:latest
        container_name: ssh-trapper
        ports:
            - "22:22"
        depends_on:
            - rsyslog
