version: "2"
services:
    rsyslog:
        image: viniciustorino/rsyslog-dockerized:latest
        restart: always
        volumes: 
            - rsyslog:/var/log
        expose:
            - "514"
    sh-trapper:
        image: viniciustorino/ssh-trapper:latest
        restart: always 
        ports:
            - "22:22"
        depends_on:
            - rsyslog
