version: "2"
services:    
    rsyslog:
        build: 
            context: . 
            dockerfile: Dockerfile-rsyslog-dockerized
        container_name: rsyslog
        restart: always
        volumes: 
            - /var/log
        expose:
            - "514"
    ssh-trapper:
        build: 
            context: .
            dockerfile: Dockerfile-ssh-trapper
        container_name: ssh-trapper
        restart: always 
        ports:
            - "22:22"
        depends_on:
            - rsyslog
